# CONFIGURATIONS for the get_data programm

# Specify time to collect web traffic
num: 8

#  Speciy maximum number of containers running
max_container_num: 10

# Specify the path to your chrome-user-data-directory
chrome_profile: "user-data-dir=/Users/bene/Library/Application Support/Google/Chrome/Default/Default"

# Specify path to your docker desktop application
docker_path: "/Applications/Docker.app"
