# CONFIGURATIONS for the get_data programm

# Specify time to collect web traffic
num: 12

# Specify timeout for website call (in case website doesn't finsih loading )
timeout: 20

#  Speciy maximum number of containers running
max_container_num: 10

# Specify the path to your chrome-user-data-directory
chrome_profile: "user-data-dir=/Users/bene/Library/Application Support/Google/Chrome/Default/Default"

# Specify path to your docker desktop application
docker_path: "/Applications/Docker.app"

# Specify time for docker to start up
docker_startup_time: 30
